### ISSUE TITLE
Network Configuration Problem ? 

### ISSUE THREAD

**Issue by vincentdchn** [jonnyhyman/ResolveCollaboration#1]
Hi, 

Thanks for making this app a reality, I really needed that ! 

Here's my setup : 
- Mac mini with Mac OS 10.14.6 with DaVinci Project Server 17.1 **as the server**
- Win 10 PC, iMac Pro (Catalina), Mac Pro Trashcan (Catalina) **as clients**

 I installed all the pip package but when I launch the .app on the server it starts, I can switch to server mode, I can enter a passsword. But when I click on OK it crashes. Log file attached :) 

[resolvecollaboration_crash_macos10.14.6.txt](https://github.com/jonnyhyman/ResolveCollaboration/files/6289681/resolvecollaboration_crash_macos10.14.6.txt)

Any ideas ? 

Thanks !

EDIT: I have the same problem on the python version on WIN10. But I have no logs. What am I missing ?

**Comment by jonnyhyman** [comment]
Hey! Thanks for giving it a try! I just pushed a [new version to the Releases](https://github.com/jonnyhyman/ResolveCollaboration/releases/tag/0.0.1) page. Try out the new macOS `.app` and let me know if it launches!

Some other things:
- `.app` files won't run on Windows 10, FYI (you may already know this)
- You don't actually need the pip packages if you're using the `.app`. Only if you're launching the app with `python resolve_collab.py`

- On Windows, that's currently the only way to launch the program. So on your Windows machine try launching `python resolve_collab.py` in a PowerShell / cmd launched from the `collab` folder
- The server-side features have only been tested on Windows, so you will be the guinea pig for a macOS server! 😄 It shouldn't be a big deal of difference!

**Comment by vincentdchn** [comment]
Hi ! 

Thanks for your fast reply. I decided to update my Mac Mini (server side) to Catalina 10.15.7.  

> .app files won't run on Windows 10, FYI (you may already know this)
- Yeah I know this, my level in code development is very bad but I have some notion haha 

> On Windows, that's currently the only way to launch the program. So on your Windows machine try launching python resolve_collab.py in a PowerShell / cmd launched from the collab folder
- Thanks, I didn't know that I needed Powershell ! 


**Server side :** 
- `.app` is also crashing. It needs the `.exec` to run properly. 
- Always showing "Resolve Database Timeout" 

**Client side :** 
- `resolve_collab.py` won't let me connect to the database and give me this ;
```
C:\Users\vince\Desktop\ResolveCollaboration-main\collab\resolve_collab.py:626: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  reader, writer = await asyncio.open_connection(S_IP, S_PORT,
```
Any ideas ? 


> The server-side features have only been tested on Windows, so you will be the guinea pig for a macOS server! 😄 It shouldn't be a big deal of difference!
- Haha it's a pleasure to experiment it for you 👍🏻 


Sorry for (maybe) dumb problems but this app is what I really need to work from home. 
Thanks again for your time on it !

**Comment by jonnyhyman** [comment]
> .app is also crashing. It needs the .exec to run properly.

This is probably because I need to code-sign the package which I haven't done yet, hoping to get to that this week some time.

> Always showing "Resolve Database Timeout"

Are both the **Server** and the **Client** connected to the WireGuard tunnel using the server and client `.conf` files made after the "AuthenticatIon" step in Resolve Mission Control?

The program assumes that the WireGuard server is where PostgreSQL can be found, and the IP of the server on the WireGuard net is `9.0.0.1`. If you're not connected through the WireGuard VPN it won't be able to find the PostgreSQL server.

I also need to make the error message "Resolve Database Timeout" more descriptive of what is actually going on.

TODO:
- [ ] Codesign `.app`
- [ ]  Make `Resolve Database Timeout` message more descriptive and accurate

**Comment by vincentdchn** [comment]
> Are both the Server and the Client connected to the WireGuard tunnel using the server and client .conf files made after the "AuthenticatIon" step in Resolve Mission Control?

Ok, so : 
- I created a password for the authentication server so it created a` .conf` file for WireGuard. **(server side)**. 
- I added a new member with an assigned IP **(server side)** 
- On client side when I try to **Make a New Connection** it is impossible. Connection is refused. So I don't understand why are you asking me if I'm connected **(both server and client side)** on WireGuard. Because this comes in the next step. 

My problem is that I can't **Make a New Connection** because one time I've got a _DeprecationWarning_ and another time I have a _Connection Refused_. 

I've got a feeling that I'm really missing something on what's happening. Because I did exactly what you wrote in the walkthrough. 

> That's my bad. Never noticed that happen on 3.7 and now building with Python 3.9. Deprecation warnings shouldn't cause the program to crash though.

Are you suggesting that I may try with Python 3.7 ? 


Another question, is it possible to erase all server configs and member that I created ? Because it starts to become very messy with all the test I'm doing ! 😃 


Thanks a lot for your time !

**Comment by jonnyhyman** [comment]
Thanks for the update! I misunderstood where you were in the process.

Some questions?
- When you try `Make New Connection` on client, do you also click `Authenticate` on the Server?
- Server : Is the firewall allowing incoming connections through TCP port 4444?
- Client : Is the `Server IP` you are trying to connect to correct? 
    - If you're testing the clients and servers on the same local network, the IP you put in must be a local IP (like `192.168.x.x` or `10.0.x.x` or whatever you get in `ifconfig` or `ipconfig`). 
    - If you're connecting through the internet, the IP must be the external IP of the router on the internet (like what you'd get from Googling "what's my ipv4")...
    - Also if you're connecting through the internet, you need to set up port forwarding on your server's router, redirecting all traffic to the server for TCP port 4444, and UDP port 51820

I realize I should add these things to the walkthrough. Thanks for your patience

**Comment by vincentdchn** [comment]
Hi ! 

> When you try Make New Connection on client, do you also click Authenticate on the Server?

Yeah I was clicking but I found that it's a matter of timing, I need to click on `Authenticate` one sec before clicking on `Make New Connection` and then it works. 


> Server : Is the firewall allowing incoming connections through TCP port 4444?
> Client : Is the Server IP you are trying to connect to correct?
> If you're testing the clients and servers on the same local network, the IP you put in must be a local IP (like 192.168.x.x or 10.0.x.x or whatever you get in ifconfig or ipconfig).
> If you're connecting through the internet, the IP must be the external IP of the router on the internet (like what you'd get from Googling "what's my ipv4")...
> Also if you're connecting through the internet, you need to set up port forwarding on your server's router, redirecting all traffic to the server for TCP port 4444, and UDP port 51820


Thanks for this, now my router is properly configured and I managed to authenticate through the internet. BUT

**Server side** : Everything is connected. I can see on Wireguard that I have a Peer, with the IP of the user I created before.  
**Client side** : Everything is connected. I can see on Wireguard that I have a Peer, with the IP (public IPV4) of my server.

### How can I connect to my Resolve Database through the internet ? : 
- Which IP do I have to put on Da Vinci Resolve to be able to connect to the database ? I tried Local IP, Public IPv4 and Wireguard IP `9.0.0.1` and none of this worked. 

I really don't know what to do next ... 

Thanks a lot for your patience too !

**Comment by jonnyhyman** [comment]
Once you're connected through Wireguard, the only IP that should work for connecting to the Resolve database through internet is `9.0.0.1`

I'm pretty mystified why that's not working for you. The only thing I can think of is maybe your database name, username and password are incorrect? 🤔

Can you confirm that if you connect to the shared database from the computer hosting it (via `127.0.0.1` in that case) it works there?

And also, the Wireguard server is the computer hosting the database?

Better yet, try clicking "Reconnect" in Resolve Mission Control and see if that comes through. This function assumes your database username and database name are the same. (Need to update to allow them to be different...)

**Comment by vincentdchn** [comment]
> Once you're connected through Wireguard, the only IP that should work for connecting to the Resolve database through internet is 9.0.0.1

Ok, then it doesn't work. 

> What error do you get from Resolve when connecting fails?

`Failed to connect to the database. Please 
check log file for more details.`


> I'm pretty mystified why that's not working for you. The only thing I can think of is maybe your database name, username and password are incorrect? 🤔

I write all the credentials on a paper sheet, so I'm 100% sure everything's right. 

> And also, the Wireguard server is the computer hosting the database?

Yes. 

> Better yet, try clicking "Reconnect" in Resolve Mission Control and see if that comes through. This function assumes your database username and database name are the same. (Need to update to allow them to be different...)

I got the same as always: `Resolve database timed out` 

I tried with a name that is the same as the database name, and surprise : it doesn't work. 

I tried wiping the server and install windows on it. Same, it doesn't work. 
Everytime I got a new error or when I managed to connect everything, I can't connect the resolve database to your app or in Resolve. 


I'm pretty discouraged right now. I feel that you're not explaining everything that you did to manage it to work. 

Thanks for your patience though ...

**Comment by jonnyhyman** [comment]
I was able to replicate your issue this morning and discovered that there is one thing I didn't include in the walkthrough that I should have.

It has to do with changing the ip-addresses values in `pg_hba.conf` (via pgAdmin) from the default server's local IP to `0.0.0.0/0` or, more ideally, `9.0.0.2/24` (and the WireGuard IPs of each client machine)

**Ultimately this is something I forgot I set up before hand, and should really be built into Resolve Mission Control**.

I will have a go at implementing the fix later this week when I have a bit more time, but I'll update this thread as soon as  I do!

It's a frustrating process for sure but our frustration paves the way for other people's ease of use :)

**Comment by jonnyhyman** [comment]
For now, @vincentdchn, try this on your Windows server:
- Go to `C:/Program Files/PostgreSQL/9.5/data`
- Open the file `pg_hba.conf` in a text editor
- Add an entry at the bottom following this template: `host  DB_NAME  DB_USER  USER_IP  md5`
    - `DB_NAME` should be the name of the database you've created
    - `DB_USER` should be the database login username
    - `USER_IP` should be `0.0.0.0/0`, which allows connections of ANY IP address. (eventually I'll make the app make one entry per authenticated user instead of this, which is slightly less secure)
- Save that file and then reboot your machine or just the PostgreSQL database

Please let me know if that works for you! 

If not, this is likely a firewall issue (worth trying to open traffic to 5432 on clients and the server)

**Comment by vincentdchn** [comment]
Hello ! 

Ok so right now I'm back on `server` on MacOS and `client` also on MacOS.

> Please let me know if that works for you!

Yeah, you totally nailed it. It was the `pg_hba.conf `.  But I had to change the method from `MD5` to `Trust`

- I'm connected through Wireguard and I can Reconnect on your app ! 🌟 
- I can see all projects and user, fantastic ! 

But last problem is: 
I can connect the database on Resolve with 9.0.0.1 but collaboration and chat is not working. Resolve is showing me the popup `Please make sure that you are not using a VPN`

Any idea ? 

> It's a frustrating process for sure but our frustration paves the way for other people's ease of use :)

Yeah totally. 😃

**Comment by jonnyhyman** [comment]
Yay! I'm so glad it connects now!

> Resolve is showing me the popup `Please make sure that you are not using a VPN`

Been diagnosing this. I think I've replicated and solved it.

#### In the Wireguard configuration for *clients*, change `AllowedIPs = 0.0.0.0/0` to `AllowedIPs = 9.0.0.0/24`

This is a mistake in the client configuration template. Todo in next release:
- [ ] Change client configuration template to write the subnet

Some background for the interested:
- I did some [packet sniffing a while back, and discovered](https://github.com/jonnyhyman/ResolveCollaboration/blob/main/tests/Discoveries.md) that Resolve's collaboration messages come through on TCP across a wide range of ports, starting with 50059, and it's not clear what the upper bound is. It seems Resolve just scans for open ports and grabs onto one.

- Contrary to DaVinci's marketing.. the message and timeline packets are completely unsecured, unencrypted! You can sniff them as plain utf-8 encoded bytes on the network (this is probably why DaVinci made collaboration local-IP-only)

![Screen Shot 2021-04-21 at 10 59 05 AM](https://user-images.githubusercontent.com/22727759/115600240-5716c600-a291-11eb-8262-017cd375401d.png)

 - With Wireguard, the TCP packets get encrypted on one end and unpacked on the other side. This makes the messages completely unreadable and cannot be decrypted without the private keys on each side.

**Comment by vincentdchn** [comment]
Hi ! Thanks for the info, it's good to know. 

> Been diagnosing this. I think I've replicated and solved it.
In the Wireguard configuration for clients, change AllowedIPs = 0.0.0.0/0 to AllowedIPs = 9.0.0.0/24

I tried but the result is that I can't connect to the server via Wireguard. Both `client` and `server` are not seing any peer connected. 
I tried `9.0.0.0/32`, `9.0.0.0/24` and `9.0.0.0/0` the last one get me connected but god knows why it disconnects randomly. 

I did exactly what I did yesterday when I managed to connect and reconnect via your app but today nothing is working. 

### Some things that I noticed : 
- When your app (in server mode) is waiting for a new connection and if you don't click `OK` on the client side within the 5 seconds it crashes 90% of the time. 
- Your app launch faster on Mojave than on Catalina.
- **Server side :** If you're not providing a `server password` and quit the page, the app is still asking for a `Database name` and a `Database password`
- Even in connected in local the app is still showing `Resolve Database Timed Out `
- If the app crashed you can't close it via the GUI, you have to close the terminal

I hope this helps !

**Comment by jonnyhyman** [comment]
> I tried 9.0.0.0/32, 9.0.0.0/24 and 9.0.0.0/0 the last one get me connected but god knows why it disconnects randomly.

Weird! Sadly `9.0.0.0/0` is an invalid network specification, so WireGuard defaults you back to to `0.0.0.0/0`, which is probably why it got things working for you again. I can confirm that `9.0.0.0/24` is the _technically correct_ thing to put for AllowedIPs, and that tests of connecting and doing collaboration through over phone's WiFi hotspot have been successful so far since I switched from the old config. 

> Some things that I noticed...

Thanks for summarizing these bugs! I'll use that it a checklist to fix some of the problems.

> today nothing is working

This might seem silly, but I had a similar thing happen, because the PostgreSQL server was down. Turning it back on by logging into it via pgAdmin or opening Resolve's Project Server tool fixed it for me. Can you confirm that your project database is running? (P.S. I'm planning to put a button in the GUI which can activate the server)

Also, I understand you're back on macOS for all the things - can you give me a sense of your network configuration? Are you connecting through a WiFi hotspot to test external connection, or some other solution?

**Comment by vincentdchn** [comment]
> Can you confirm that your project database is running? (P.S. I'm planning to put a button in the GUI which can activate the server)

Yeah, Da Vinci Resolve Project Server was running and I was also connected to the database with PgAdmin 3.

> can you give me a sense of your network configuration? Are you connecting through a WiFi hotspot to test external connection, or some other solution?

Ok so here's configuration : 

I have a fiber connection, my ISP router is in bridge mode so I can use my NetGear XR500 as a DHCP server and easily forward ports. 

- Mac Mini (Mac OS Mojave) for **SERVER** (local), connected to the NetGear XR500 with Wifi. `10.0.0.4`
- MacBook Pro 13" (Catalina) for **CLIENT 1** (over internet) connected to my iPhone's Hotspot(4G connection). `public IPV4`
- MacBook Pro 16" (Big Sur) for **CLIENT 2** (local), connected to the NetGear XR500 with Wifi. `10.0.0.7`

On my NetGear XR500, I opened the port `51820` , `5432` , `4444` and forwarded them to `10.0.0.4` (**SERVER**)

Do you need more infos ? 

I tested the "DaVinci" way of Collaboration and Shared Database on Wifi and everything's very smooth. So I don't think being plugged to my router can change something right ? 

> Lastly, I'll get a setup going for myself as a macOS server, so I can test some of the issues you're having.

Yay, welcome in my world 🤝 !

**Comment by jonnyhyman** [comment]
> On my NetGear XR500, I opened the port 51820 , 5432 , 4444 and forwarded them to 10.0.0.4 (SERVER)

Try disabling the `5432` port forward? I've noticed that things fail if the server is accessible through the same interface Wireguard is redirecting from. Maybe the packets get mixed up. The server should only be accessible on the Wireguard subnet (`9.0.0.0/24`). I'll replicate your setup on my end and see if I have a similar problem.

> Yay, welcome in my world 🤝 !

Thanks! I'll try it out a little later today (Pacific time) and let you know what I find! :)


_FYI, on the next release I'm planning to put Wireguard on `4444`, so that all you have to do is open TCP and UDP on 4444_

**Comment by jonnyhyman** [comment]
I tried port forwarding `5432` and it didn't replicate your issue - collaboration features, the app reconnect, everything worked just fine.

Going to try out macOS server now.

**Comment by vincentdchn** [comment]
> I tried port forwarding 5432 and it didn't replicate your issue - collaboration features, the app reconnect, everything worked just fine.

Wow, that's weird. 

I was thinking, as I'm on MacOS for the server side, I can't execute this part of the walkthrough : 

> For a Windows server, to give clients access your internet connection, you must modify the internet adapter you're connected to the internet with. For me, that's Ethernet 2
Go to the Sharing tab, check both boxes, and select the Wireguard server you created as the Home network connection

Maybe it has something to do with my problem ?

**Comment by jonnyhyman** [comment]
Okay so I've been digging about and found [this guide for Wireguard Servers on macOS](https://barrowclift.me/post/wireguard-server-on-macos). Turns out the Wireguard app GUI is sandboxed so heavily by macOS that it can't do the important firewall passthroughs.

Probably the simplest solution is to use a Windows server if you can!

I'm going to see how many of the steps in the guide above I can implement as a python script, so we can bundle it in Resolve Mission Control

**Comment by jonnyhyman** [comment]
I also discovered: For clients the reason you were probably getting randomly disconnected is because you need to add:
```# If you're be behind a NAT, this will keep the connection alive.
PersistentKeepalive = 25
```
(since you've got that NAT going on with your router's bridge mode)

**Comment by jonnyhyman** [comment]
FYI: So at this point there's a big long list of things to improve in the app and features to add and fix. I will slowly be building it out but getting to full functionality will take a few weeks probably, if not months (in-between other work)

**Comment by jonnyhyman** [comment]
All the above issues have been solved and tested (except the long time to open the client .app, that's a bigger issue)

@vincentdchn please check out the new Beta version 0.1.0, and I'll reopen this issue if you keep having the same problem

**Comment by vincentdchn** [comment]
Hi ! Thanks for the release, I'll test it out as soon as I get back to work :)
